### ISSUE TITLE
dist takes parameters that are silently ignored when passed sketch files

### ISSUE THREAD

**Issue by hgbrian** [onecodex/finch-rs#28]
This works as expected: ```finch dist -p -n100 -k100 *.fasta```
This does not work as expected: ```finch dist -p -n100 -k100 *.fasta.sk```

The parameters k and n appear to be ignored when a sketch is passed to dist.
(It does check if k>256 though.)

It makes sense that k and n would have no effect since the sketch already has a kmer length and a num hashes. However, this caused me some confusion for a while...

**Comment by bovee** [comment]
We should almost certainly blow up in this case.

The code path here is complicated in that it tries to use the sketch to determine the parameters so that e.g. `finch dist` can intelligently know how to compare a sketch to a FASTA. Unfortunately, this seems to be too complicated in that we've hit a few cases where how we choose the reference parameters is completely counterintuitive (see also #24) and we should probably clean up how we're doing argument parsing and parameter selection.

**Comment by hgbrian** [comment]
works for me, thanks!
